spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        namespace: nhzx
        group: DEFAULT_GROUP
        ip: 127.0.0.1
      config:
        namespace: nhzx
        file-extension: yaml
  config:
    import:
      - nacos:shared-spring.yaml
      - nacos:shared-redis.yaml
      - nacos:shared-mybatis.yaml
      - nacos:shared-logs.yaml
logging:
  level:
    com.nuaa: debug
