server:
  port: 8088  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: trade-service
nhzx:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.nuaa.trade.controller
    title: 南航智学 - 交易中心接口文档
    description: 该服务提供购物车、订单管理等功能
    contact-name: 开发组
    contact-url: https://localhost
    contact-email: dev@localhost
    version: v1.0
  jdbc:
    database: nhzx_trade
  auth:
    resource:
      enable: true
      excludeLoginPaths:
        - "/order-details/enrollNum"
