server:
  port: 8086  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: course-service
  main:
    allow-circular-references: true
nhzx:
  swagger:
    enable: true
    package-path: com.nuaa.course.controller
    title: 南航智学 - 课程系统接口文档
    description: 该服务包含课程管理相关功能
    contact-name: 开发组
    contact-url: https://localhost
    contact-email: dev@localhost
    version: v1.0
    enableResponseWrap: true
  auth:
    resource:
      enable: false
  jdbc:
    database: nhzx_course
