server:
  port: 8092  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: promotion-service
nhzx:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.nuaa.promotion.controller
    title: 南航智学课堂 - 促销中心接口文档
    description: 该服务包含优惠促销有关的功能
    contact-name: 开发组
    contact-url: https://localhost
    contact-email: dev@localhost
    version: v1.0
  jdbc:
    database: nhzx_promotion
  auth:
    resource:
      enable: true # 开启登录拦截的功能
  mq:
    listener:
      retry:
        stateless: false # 无状态
  promotion:
    aes:
      key: nhzx-test-key-in
      iv: nhzx-test-ivinit
